### PR TITLE
Enable save and load for Mastery Checks and Consultations, update PPP and UG, fix output strings

### LINKED ISSUE #244: [PE-D] Re-launching app does not load Mastery Check or Consultation added in last launch of app
I exitted the app and relaunched it before checking the various tab for the content I created before. When I checked the Mastery Check and Consultation tab however, the Consultations and Mastery Checks I have made before is gone however. 

I have also tried to 'relogin' before checking again, but it still does not show up.

I am unsure if this is because of the login/authentication issue but just a note on the issue.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: rachel170/ped#7

### LINKED ISSUE #314: Add feature descriptions to Consultation and MC related commands

### PR DESCRIPTION
**Pull request by wireseo**
Fixes #314 
Fixes #244

### CODE REVIEW

File: src/main/java/seedu/jarvis/logic/commands/add/AddCommand.java [hunk 1]
```diff
@@ -21,7 +21,8 @@
             + "add -d DESCRIPTION d/YYYY-MM-DD t/HH:MM: Add deadline with DESCRIPTION at specified date and time\n";
 
     public static final String MESSAGE_MISSING_DESCRIPTION = "Please include the DESCRIPTION";
-    public static final String MESSAGE_MISSING_DATE = "Please include DATE and TIME d/YYYY-MM-DD t/HH:MM";
```
Comment (Asuraxsoul) [inline src/main/java/seedu/jarvis/logic/commands/add/AddCommand.java:24]: I believe the TaskCommandParser needs MESSAGE_MISSING_DATE instead of MESSAGE_MISSING_INFO because Task dont have NAME variable.

File: src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java [hunk 2]
```diff
@@ -140,7 +140,7 @@ public static LocalDateTime parseTimedTaskTime(String[] nameKeywords, int length
 
         } else if (!hasDatePrefix || !hasTimePrefix) {
             throw new ParseException(
-                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_MISSING_DATE));
+                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_MISSING_INFO));
```
Comment (Asuraxsoul) [inline src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java]: I think this error message is incorrect, I might still need the previous version error message.

**Review by Asuraxsoul — CHANGES_REQUESTED** [review]
Great effort for implementing these features!

File: src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java (hunk 2 above)
Comment (wireseo) [reply src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java]: Okay, just a sec!

File: src/main/java/seedu/jarvis/logic/commands/edit/EditMasteryCheckCommand.java [hunk 3]
```diff
@@ -102,7 +104,7 @@ public boolean equals(Object other) {
      * corresponding field value of the mastery check.
      */
     public static class EditMasteryCheckDescriptor {
-        private boolean passed;
+        private boolean hasPassed;
```
Comment (ngzhenteng) [inline src/main/java/seedu/jarvis/logic/commands/edit/EditMasteryCheckCommand.java:107]: Thank  you for adapting to the coding standards!

File: src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java (hunk 2 above)
Comment (wireseo) [reply src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java]: Just pushed a new commit, hopefully it should work now!

File: src/main/java/seedu/jarvis/model/ModelManager.java [hunk 4]
```diff
@@ -423,11 +423,11 @@ public void updateMasteryChecksList(Predicate<MasteryCheck> predicate) {
         filteredMasteryChecks.setPredicate(predicate);
     }
 
-    @Override
+    /*
```
Comment (ngzhenteng) [inline src/main/java/seedu/jarvis/model/ModelManager.java:426]: Do remember to remove the comment once we are certain that we dont need this method :)

File: src/main/java/seedu/jarvis/storage/JsonAdaptedMasteryCheck.java [hunk 5]
```diff
@@ -1,17 +1,27 @@
...
+
 import com.fasterxml.jackson.annotation.JsonProperty;
 
+import seedu.jarvis.commons.exceptions.IllegalValueException;
+import seedu.jarvis.model.masterycheck.MasteryCheck;
+
+
 public class JsonAdaptedMasteryCheck {
+    public static final String MISSING_FIELD_MESSAGE_FORMAT = "Mastery Check's %s field is missing!";
+    public static final String INVALID_DATE_TIME_FORMAT = "Date time format is wrong! Please follow format: "
```
Comment (ngzhenteng) [inline src/main/java/seedu/jarvis/storage/JsonAdaptedMasteryCheck.java:14]: Great, a more verbose error message will help with the practical exam!

File: src/main/java/seedu/jarvis/storage/JsonAdaptedMasteryCheck.java [hunk 6]
```diff
@@ -20,4 +30,47 @@ public JsonAdaptedMasteryCheck(@JsonProperty("studentName") String studentName,
...
+        dateAndTime = source.getDateAndTime().toString();
+        passed = source.isPassed() ? "T" : "F";
+    }
+
+    /**
+     * Converts this Jackson-friendly adapted Mastery Check object into the model's {@code MasteryCheck} object.
+     * @return MasteryCheck
+     * @throws IllegalValueException if there were any data constraints violated in the adapted Mastery Check.
+     */
+    public MasteryCheck toModelType() throws IllegalValueException {
```
Comment (ngzhenteng) [inline src/main/java/seedu/jarvis/storage/JsonAdaptedMasteryCheck.java:49]: Thank you for implementing this method, we will be able to save and retrieve MCs now!

**Review by ngzhenteng — COMMENTED** [review]
LGTM, Thank you!

**Review by Asuraxsoul — APPROVED** [review]

File: src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java (hunk 2 above)
Comment (Asuraxsoul) [reply src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java]: THank you! 👍
