### PR TITLE
GUI/invalid messages

### LINKED ISSUE #32: Update GUI with current week and topic

### LINKED ISSUE #241: [PE-D] Add command's error message a bit vague
I find the 'add' command's invalid flag a bit vague in informing the user what went wrong. Perhaps providing an example of the general command format for add or specifying what is considered a valid can be helpful to a new user.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: rachel170/ped#4

### LINKED ISSUE #270: Change colour of tabs in GUI

### PR DESCRIPTION
**Pull request by wilinetan**
Fixes #32
Fixes #241
Fixes #270

### CODE REVIEW

File: src/main/java/seedu/jarvis/model/util/SampleDataUtil.java [hunk 1]
```diff
@@ -11,7 +13,7 @@
  * Contains utility methods for populating {@code AddressBook} with sample data.
  */
 public class SampleDataUtil {
-    public static Student[] getSamplePersons() {
```
Comment (peironggg) [inline src/main/java/seedu/jarvis/model/util/SampleDataUtil.java:14]: Thanks for refactoring names!

File: src/main/java/seedu/jarvis/ui/MainWindow.java [hunk 2]
```diff
@@ -230,6 +244,29 @@ private void setGreeting() {
         greeting.textProperty().bind(logic.getGreeting());
     }
 
+    /**
+     * Sets the week and topic
+     */
+    private void setWeekAndTopic() {
```
Comment (peironggg) [inline src/main/java/seedu/jarvis/ui/MainWindow.java:250]: Awesome way to calculate how many weeks it has been since the start of the semester 👍

File: src/main/java/seedu/jarvis/ui/MainWindow.java [hunk 3]
```diff
@@ -284,7 +321,7 @@ private void handleSourceAcademy() {
     private void handleUserGuide() {
         try {
             Desktop.getDesktop()
-                    .browse(URI.create("https://ay2021s1-cs2103t-w11-2.github.io/tp/UserGuide.html#quick-start"));
+                    .browse(URI.create(USER_GUIDE_URL));
```
Comment (peironggg) [inline src/main/java/seedu/jarvis/ui/MainWindow.java:324]: nice abstraction

File: src/test/java/seedu/jarvis/testutil/TypicalQuests.java [hunk 4]
```diff
@@ -11,9 +16,37 @@
     public static final Quest TEST_QUEST = new Quest(TEST_QUEST_TITLE, TEST_QUEST_DEADLINE);
 
     public static final Quest TEST_QUEST_COPY = new Quest(TEST_QUEST_TITLE, TEST_QUEST_DEADLINE);
+    public static final Quest RUNIC_CARPETS = new QuestBuilder().withTitle("Runic Carpets")
```
Comment (peironggg) [inline src/test/java/seedu/jarvis/testutil/TypicalQuests.java:19]: Thumbs up for creating tests!
