### PR TITLE
Refactor consultation class and fix add and view consultations

### LINKED ISSUE #211: Fix View and Add Consultations and Mastery Checks Commands (post-refactoring / re-structuring consultation class)

### LINKED ISSUE #217: Add JSON Adapted Consultation and MasteryCheck

### PR DESCRIPTION
**Pull request by wireseo**
Fixes #217
Fixes #211

### CODE REVIEW

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 1]
```diff
@@ -91,6 +93,16 @@ public ReadOnlyAddressBook getAddressBook() {
         return model.getFilteredTaskList();
     }
 
+    @Override
```
Comment (ngzhenteng) [inline src/main/java/seedu/address/logic/LogicManager.java:96]: Great addition, consultation features should work well now!

**Review by ngzhenteng — COMMENTED** [review]
LGTM! thank you for the thorough optimisations
